version: "3.7"

services:
  #   redis:
  #     container_name: redis
  #     image: redis
  #     ports:
  #       - "127.0.0.1:6379:6379"

  #   mongo:
  #     container_name: mongodb
  #     hostname: mongodb
  #     restart: always
  #     image: mongo
  #     command:
  #       - "-f"
  #       - "/etc/mongod.conf"
  #     ports:
  #       - "127.0.0.1:27017:27017"
  #     volumes:
  #       - ~/mongo:/data/db
  #       - ./mongod.conf:/etc/mongod.conf

  node_app:
    container_name: node_app
    restart: always
    image: fake-server:v1
    environment:
      PORT: 3001
      NODE_ENV: DEV
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
