image: node:lts-alpine

variables:
  FOLDER_NAME: fake-client
  FILE_NAME: client_$CI_PIPELINE_IID.zip

stages:
  - build
  - deploy

build_job:
  stage: build
  only:
    - tags
    - /^build/
  cache:
    paths:
      - $FOLDER_NAME/node_modules/
    key: "$FOLDER_NAME_node_modules"
  script:
    - apk add --no-cache zip
    - cd $FOLDER_NAME
    - npm i
    - npm run build-and-zip
    - mv client.zip $FILE_NAME
  artifacts:
    expire_in: 60d
    paths:
      - $FOLDER_NAME/$FILE_NAME

deploy_job:
  image: alpine
  stage: deploy
  when: manual
  only:
    - tags
    - /^build/
  before_script:
    - which ssh-agent || ( apk --update add openssh-client )
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | ssh-add - > ~/.ssh/id_rsa
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  dependencies:
    - build_job
  script:
    - cd $FOLDER_NAME
    - scp -P $SSH_PORT ./$FILE_NAME $USER@$HOST:/home/$USER/$FILE_NAME
    - >
      ssh -p $SSH_PORT $USER@$HOST "unzip -o ./$FILE_NAME -d /var/www/html_new && rm -rf ./$FILE_NAME 
      && cd /var/www/ && rm -rf ./html_back && mv ./html ./html_back && mv ./html_new ./html"
  variables:
    GIT_STRATEGY: none
